version: "3.7"

services:
  postgres:
    container_name: iam-postgres
    restart: unless-stopped
    tty: true
    image: postgres
    ports:
      - 5444:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - iam-simulation-network
    volumes:
      - iam-simulation-db:/var/lib/postgresql/data
  keycloak:
    container_name: iam-keycloak
    restart: unless-stopped
    tty: true
    # --spi-theme params for develop custom themes in Keycloak
    command: ["start-dev", "--http-port", "8180", "--spi-theme-static-max-age", "-1", "--spi-theme-cache-themes", "false", "--spi-theme-cache-templates", "false"]
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8182:8180
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=super
    networks:
      - iam-simulation-network

networks:
  iam-simulation-network:
    name: iam-simulation-network

volumes:
  iam-simulation-db:
    name: iam-simulation-db